import MainAuthComponent from "@/src/components/Auth.tsx/AuthMainContainer";
import MainLayout from "@/src/components/MainLayout/MainLayout";
import type { Metadata } from "next";
import React, { ReactNode, Suspense } from "react";

type Props = {};

export const metadata: Metadata = {
  title: "BOE Invoice Report",
  description:
    "Invoice-level breakdown of your Bills of Entry — values, duties and reconciliation status — generated by Customs IQ.",
  keywords: [
    "BOE invoice report",
    "Bill of Entry invoice",
    "BOE invoice value",
    "Customs invoice report",
    "Customs IQ invoice report",
  ],
  alternates: {
    canonical: "/reports/boe-reports/invoice",
  },
  openGraph: {
    title: "BOE Invoice Report | Customs IQ",
    description:
      "Invoice-level Bill of Entry report — values, duties and reconciliation.",
    url: "/reports/boe-reports/invoice",
    type: "website",
    siteName: "Customs IQ",
  },
  twitter: {
    card: "summary",
    title: "BOE Invoice Report | Customs IQ",
    description:
      "Invoice-level Bill of Entry report — values, duties and reconciliation.",
  },
  robots: {
    index: false,
    follow: false,
  },
};

const layout = ({ children }: { children: ReactNode }) => {
  return <div>{children}</div>;
};

export default layout;
